### ISSUE TITLE
ReadMe 1st example doesn't work with Julia 1.2

### ISSUE THREAD

**Issue by rlecover007** [gsoleilhac/NSGAII.jl#3]
With some updates, the readme doesn't quite work as written. Specifically, the calls to bitrand need to be changed, and you need to call `using Random, LinearAlgebra`

The following worked for me:
`using NSGAII
using Random
using LinearAlgebra
n = 20 #Number of items
p1 = [77,94,71,63,96,82,85,75,72,91,99,63,84,87,79,94,90,60,69,62] #Coeffs objective 1
p2 = [65,90,90,77,95,84,70,94,66,92,74,97,60,60,65,97,93,60,69,74] #Coeffs objective 2
w = [80,87,68,72,66,77,99,85,70,93,98,72,100,89,67,86,91,79,71,99] #Items weights
c = 900 #Knapsack capacity

rng = MersenneTwister(1234);
popsize = 100
nbgen = 200

init() = bitrand(rng, n) #our genotype is a binary vector of size n, initialized randomly
z(x) = dot(x, p1), dot(x, p2) #and our objectives are the sum of the items we pick

function CV(x)
    sumW = dot(x, w)
    return sumW <= c ? 0 : sumW - c
end

#We can now call
result = nsga_max(popsize, nbgen, z, init, fCV = CV)
`

**Comment by gsoleilhac** [comment]
Good point, I updated the README :). I don't think the call to `bitrand` needs to be changed though, it can still use the global rng by default

**Comment by rlecover007** [comment]
You're right-it works as is once you import Random.
